In [2]:
from tpot import TPOTClassifier
from sklearn.datasets import load_iris
from sklearn.cross_validation import train_test_split

In [4]:
iris = load_iris()
iris.data[0:5], iris.target

(array([[ 5.1,  3.5,  1.4,  0.2],
        [ 4.9,  3. ,  1.4,  0.2],
        [ 4.7,  3.2,  1.3,  0.2],
        [ 4.6,  3.1,  1.5,  0.2],
        [ 5. ,  3.6,  1.4,  0.2]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]))

In [3]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target,
                                                    train_size=0.75, test_size=0.25)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [4]:
tpot = TPOTClassifier(generations=5)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))

0.975757575758


In [5]:
tpot.export('tpot_iris_pipeline.py')

In [7]:
# %load tpot_iris_pipeline.py
import numpy as np
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import ExtraTreesClassifier, VotingClassifier
from sklearn.feature_selection import SelectPercentile, f_classif
from sklearn.kernel_approximation import RBFSampler
from sklearn.pipeline import make_pipeline, make_union
from sklearn.preprocessing import FunctionTransformer

# NOTE: Make sure that the class is labeled 'class' in the data file
#tpot_data = np.recfromcsv('PATH/TO/DATA/FILE', delimiter='COLUMN_SEPARATOR', dtype=np.float64)
#tpot_data = np.hstack((iris.data, np.expand_dims(iris.target, axis=1)))
#features = np.delete(tpot_data.view(np.float64).reshape(tpot_data.size, -1), tpot_data.dtype.names.index('class'), axis=1)
features = iris.data
target = iris.target
training_features, testing_features, training_classes, testing_classes = \
    train_test_split(features, target, random_state=42)

exported_pipeline = make_pipeline(
    RBFSampler(gamma=0.55),
    SelectPercentile(percentile=8, score_func=f_classif),
    ExtraTreesClassifier(criterion="entropy", max_features=0.44, n_estimators=500)
)

exported_pipeline.fit(training_features, training_classes)
results = exported_pipeline.predict(testing_features)

In [9]:
type(exported_pipeline.fit(training_features, training_classes))

sklearn.pipeline.Pipeline

In [10]:
from sklearn.decomposition import PCA
from sklearn2pmml.decoration import ContinuousDomain
import pandas
import sklearn_pandas

In [47]:
import sklearn

In [ ]:
from sklearn2pmml import sklearn2pmml

In [116]:
iris_mapper = sklearn_pandas.DataFrameMapper([
    (["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"], 
#      RBFSampler(gamma=0.55)),
#      [ContinuousDomain(), PCA(n_components = 3)]
#      [ContinuousDomain(), RBFSampler(gamma=0.55)]),
#      [SelectPercentile(percentile=8, score_func=f_classif)]
    ),
    ("Species", None)
])

# iris_classifier = sklearn.linear_model.LogisticRegressionCV()
iris_classifier = ExtraTreesClassifier(criterion="entropy", max_features=0.44, n_estimators=500)

iris = load_iris()
iris_df = pandas.concat((pandas.DataFrame(iris.data[:, :], columns = ["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"]), pandas.DataFrame(iris.target, columns = ["Species"])), axis = 1)
iris = iris_mapper.fit_transform(iris_df)
iris_X = iris[:, :-1]
iris_y = iris[:, -1]

iris_classifier.fit(iris_X, iris_y)

sklearn2pmml(iris_classifier, iris_mapper, "cam_iris.pmml", with_repr = True, debug=True)

ValueError: need more than 1 value to unpack

In [99]:
iris = load_iris()
print iris.data.shape
print iris_X.shape

(150, 4)
(150, 3)


In [93]:
print iris_X.shape
print iris_y.shape

(150, 3)
(150,)


In [85]:
iris

array([[-0.08243959,  0.07485807,  0.13500864, ...,  0.05458325,
         0.10707913,  0.        ],
       [-0.08013961,  0.14142125,  0.08167507, ...,  0.07093541,
         0.12377177,  0.        ],
       [-0.0735397 ,  0.14130325,  0.09460401, ...,  0.09117099,
         0.13857378,  0.        ],
       ..., 
       [ 0.093769  ,  0.05136669,  0.12508146, ...,  0.12087511,
        -0.07438504,  2.        ],
       [ 0.12386193,  0.11440241,  0.05728974, ...,  0.05331696,
        -0.10202548,  2.        ],
       [ 0.05633671, -0.04819906,  0.11233171, ...,  0.07447886,
        -0.14084731,  2.        ]])

In [107]:
#
# Step 1: feature engineering
#

from sklearn.datasets import load_iris
from sklearn.decomposition import PCA

from sklearn2pmml.decoration import ContinuousDomain

import pandas
import sklearn_pandas

iris = load_iris()

iris_df = pandas.concat((pandas.DataFrame(iris.data[:, :], columns = ["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"]), pandas.DataFrame(iris.target, columns = ["Species"])), axis = 1)

iris_mapper = sklearn_pandas.DataFrameMapper([
    (["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"], 
     [ContinuousDomain(), PCA(n_components = 3)]),
    ("Species", None)
])

iris = iris_mapper.fit_transform(iris_df)


#
# Step 2: training a logistic regression model
#

from sklearn.linear_model import LogisticRegressionCV

iris_X = iris[:, :-1]
iris_y = iris[:, -1]

iris_classifier = LogisticRegressionCV()
iris_classifier.fit(iris_X, iris_y)

#
# Step 3: conversion to PMML
#

from sklearn2pmml import sklearn2pmml

sklearn2pmml(iris_classifier, iris_mapper, "LogisticRegressionIris.pmml", with_repr = True, debug=True)

('python: ', '2.7.11')
('sklearn: ', '0.17.1')
('sklearn.externals.joblib:', '0.9.4')
('sklearn_pandas: ', '1.1.0')
('sklearn2pmml: ', '0.11.1')
java -cp /Users/cameron2/.local/lib/python2.7/site-packages/sklearn2pmml/resources/guava-19.0.jar:/Users/cameron2/.local/lib/python2.7/site-packages/sklearn2pmml/resources/istack-commons-runtime-2.21.jar:/Users/cameron2/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jaxb-core-2.2.11.jar:/Users/cameron2/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jaxb-runtime-2.2.11.jar:/Users/cameron2/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jcommander-1.48.jar:/Users/cameron2/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jpmml-converter-1.1.0.jar:/Users/cameron2/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jpmml-sklearn-1.1.1.jar:/Users/cameron2/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jpmml-xgboost-1.1.0.jar:/Users/cameron2/.local/lib/python2.7/site-packages/sklearn2pmml/reso